version: '3.8'

services:
  frontend:
    image: sep-drive-frontend:latest
    ports:
      - "4200:80"

  backend:
    image: sep-drive-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - ./h2data:/data
      - ./uploads:/app/uploads
    environment:
      SUPER_CODE: super1
      JWT_SECRET: superdupersecretkey324chasdasfwerqwre
